POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "account": "13800138001",
  "password": "MyPass123",
  "tenant_id": 1,
  "real_name": "张三"
}

###
### 登录
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "account": "admin",
  "password": "admin"
}


### 登出
POST http://localhost:8080/api/v1/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ0ZW5hbnRfaWQiOjEsInJvbGUiOiJ1c2VyIiwic2lkIjoiZmE5ZDhhNTgtMWI4MC00YmVmLTkxMDgtYzY4NWE4NzY2NDRjIiwiZXhwIjoxNzc2NzU4NTY5fQ.0cGs1l5-VEFWqeFNvSoqiD8M8KR7vRgPQCZk9IGL7c8

###
GET http://localhost:8080/api/v1/health
#Authorization: Bearer {{user}}

###
GET http://localhost:8080/api/v1/cms/ping
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ0ZW5hbnRfaWQiOjEsInJvbGUiOiJ1c2VyIiwic2lkIjoiZDJlZmNkOWQtMWM5MS00NWRhLTg1NDUtOWIyYWQ2NjBhMmM5IiwiZXhwIjoxNzc2NzYxNjIwfQ.o6gdSdY5lV4NMsnKgHqpb5IeEmZ9hm7XSnPTL6QuLCg


###
POST http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ0ZW5hbnRfaWQiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzc2NjY2NjUwfQ.DYUQgVX7VzEkr0OvhyTi7I9Yqg6PkU5GE_o2LeWUBto
{
  "name": "test",
  "email": "test",
  "password": "password"
}

###
PUT http://localhost:8080/api/v1/users/:id

###
DELETE http://localhost:8080/api/v1/user/:id





