app:
  name: xin
  env: dev # dev prod
  host: 0.0.0.0
  port: 8080

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: xin
  sslmode: disable
  max_open_conns: 100
  max_idle_conns: 20
  conn_max_lifetime_sec: 300
  conn_max_idle_time_sec: 60

redis:
  host: 192.168.151.176
  port: 6379
  password: ""
  db: 0

  # enabled=false ：Redis 完全关闭，不初始化客户端
  # enabled=true && required=false ：Redis 不可用时降级继续启动
  # enabled=true && required=true ：Redis 不可用时启动失败（更严格）
  enabled: true
  required: false
  pool_size: 20
  min_idle_conns: 5
  pool_timeout_sec: 4
  idle_timeout_sec: 300
  max_conn_age_sec: 0

jwt:
  secret: your-secret-key
  expire: 3600
  refresh_expire: 86400

saas:
  mode: shared # shared | schema | database

log:
  dir: logs
  level: info # debug | info | warn | error

module:
  - system
  - auth
  - weixin

apps:
  - cms
